### ISSUE TITLE
Namespace and plugin usage

### ISSUE THREAD

**Issue by delvedor** [oxsav/fastify-firebase-auth#1]
Hi! Thank you for trying Fastify and create a plugin! :)

Just a nit, we are already using the namespace `auth` inside Fastify for the [`fastify-auth`](https://github.com/fastify/fastify-auth) plugin, could be a good idea rename this namespace in something like `fbauth` so something like that.

Again, thank you for the plugin! Would be nice write it in a way to integrate it with [`fastify-auth`](https://github.com/fastify/fastify-auth) an agnostic authentication manager that supports multiple authentication methods at the same time.
What do you think?

Cheers!

**Comment by oxsav** [comment]
Hey! Probably fastify-fbauth will be confused with `facebook-auth` or something like that, that's why I gave the name `firebase-fastify-auth`. 

About the other part of integrate it with `fastify-auth` I think it is a good idea, will have to take a good look to that and try to do it. 

Thank you for the input. :)

**Comment by delvedor** [comment]
> Hey! Probably fastify-fbauth will be confused with facebook-auth or something like that, that's why I gave the name firebase-fastify-auth.

You are right, but I was referring to the namespace that you are registering inside Fastify.
At the moment I can access your plugin apis via `fastify.auth`. Would be nice update that namespace to something slightly different and more specific.

> About the other part of integrate it with fastify-auth I think it is a good idea, will have to take a good look to that and try to do it.

If you have questions please write here or in the [`fastify-auth`](https://github.com/fastify/fastify-auth) repo, I'll be happy to help! :)
