### ISSUE TITLE
Catch errors and set response type.

### ISSUE THREAD

**Issue by lgertel** [oxsav/fastify-firebase-auth#3]
@oxsav Hello! I'm trying to use this plugin in my project. At this moment I'm not sure how to deal with the different possible responses when calling a specific method.
On the plugin definition, the methods catch() call possible errors, like this one:
```
createUserWithEmailAndPassword: (email, password) => auth()
      .createUserWithEmailAndPassword(email, password)
      .catch(setError)
```

The problem is, in my implementation I always receive a 200 response with a simple JSON body and with no way to catch this errors and change the response on my side.

```
{ statusCode: 'auth/wrong-password',
  message:
   'The password is invalid or the user does not have a password.' }
```

This is a 200 return from a signInWithEmailAndPassword call. I would like to get the error on my side.
What I'm missing?

Thanks

**Comment by oxsav** [comment]
The firebase authentication "API", is returning all the errors as success what is odd. If It was an actual error it should fall in a "catch" method not in the "then".

I will take a look to see if something changed in the firebase API.

**Comment by lgertel** [comment]
In my tests they returned errors. I think that is related with the catch inside the plugin.
To be able to do something, I'm changing your setError obj:
```
const setError = error => ({
  error: true,
  statusCode: error.code,
  message: error.message
})
```
On the 'client':
```
const {email, password} = request.body;
    const response = await fastify.auth.signInWithEmailAndPassword(email, password);

    if (response['error'] == true) {
      reply.code(500)
    }

    return response
```

And then dealing on front. Not beautiful, but works.

**Comment by oxsav** [comment]
Yes you are right. 
I'll try to find a better way to handle the errors from the firebase. 
Thanks for using it :)

**Comment by lgertel** [comment]
Great! I'll fork this project and maybe I'll be able to help you too. 
Can we leave this open to future updates?

**Comment by oxsav** [comment]
Ofc. feel free to do Pull Requests and give ideas. thanks !
